# -*- coding: utf-8 -*-
"""nps

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gG_alHFVUZHk-MEL7n9f8LifbqQBbgzn
"""

import streamlit as st
from enum import unique
import pandas as pd
import numpy as np
import seaborn as sns
import unicodedata
from datetime import date
import matplotlib.pyplot as plt
import plotly.express as px

df = pd.read_excel('nps.xlsx')
df['Cantidad Del Np'] = df['Cantidad Del Np'].fillna(1) # reemplazar los vacios por 1
df['Valor Unitario Del Np'] = df['Valor Unitario Del Np'].fillna(0) # reemplazar los vacios por 0
df1 = df.replace("SIN DATO", None)

print("")
print("******************* INFORMACION GENERAL DE LA BASE INICIAL DE LOS NPS:*********************")
#print(df.info())
print("")

df1['Valor Total Del NP'] = df.iloc[:, 7] * df1.iloc[:, 16] # multiplicacion

hoy = pd.Timestamp.today().normalize() # primero se debe obtener el valor numerico de la fecha de HOY
fecha_base = pd.Timestamp('30-12-1899') #día 0 es el 31 de diciembre de 1899
hoy = (hoy - fecha_base).days
df1['Dias desde el ingreso del NP al IDU'] = (hoy - df1['Fecha Ingreso C']) # resta de fechas
df1['Dias de respuesta'] = (hoy - df1['Fecha Respuesta C']) # resta de fechas
df1['Dias de ingreso al grupo np'] = (hoy - df1['Fecha De Ingreso Al Grupo De Nps C'])
df1['Dias desde envio correo'] = (hoy - df1['Fecha Envio De Email Al Supervisor C'])

df1['Dias de respuesta'] = df1['Dias de respuesta'].replace(hoy, np.nan) # reemplazar hoy por ningun valor
df1['Dias de ingreso al grupo np'] = df1['Dias de ingreso al grupo np'].replace(hoy, np.nan) # reemplazar hoy por ningun valor
df1['Dias desde envio correo'] = df1['Dias desde envio correo'].replace(hoy, np.nan) # reemplazar hoy por ningun valor


#***************** LÍNEAS PARA IDENTIFICAR EL ÚLTIMO REPORTE O GESTIÓN DE CADA NP DE ACUERDO AL CONTRATO *************
final = df1.groupby(['Contrato Obra', 'Codigo Np']).last().reset_index()
final.to_excel('bloque verde.xlsx', index=False)

df2 = pd.read_excel('bloque verde.xlsx')

# lineas para extraer el mes de la fecha de ingreso del np
df2['Fecha Ingreso C'] = pd.to_datetime(df2['Fecha Ingreso C'], unit='D', origin='30-12-1899', errors='coerce')

# Diccionario de traducción
meses_espanol = {
     1: 'Enero', 2: 'Febrero', 3: 'Marzo', 4: 'Abril',
     5: 'Mayo', 6: 'Junio', 7: 'Julio', 8: 'Agosto',
     9: 'Septiembre', 10: 'Octubre', 11: 'Noviembre', 12: 'Diciembre'}

 # 3. Crear la nueva columna extrayendo el número del mes y mapeando
df2['Mes'] = df2['Fecha Ingreso C'].dt.month.map(meses_espanol)

# Obtener los valores únicos de cada columna
contratos_unicos = df2['Contrato Obra'].unique()
codigos_unicos = df2['Codigo Np'].unique()

df2['Contratos Unicos'] = pd.Series(contratos_unicos)
df2['Codigos NP Unicos'] = pd.Series(codigos_unicos)

#df2.to_excel('bloque verde2.xlsx', index=False)

# ************ LINEAS PARA REALIZAR FILTROS VARIOS ************************

print('********************* FILTRO 1: conteo por estado de NPs ****************')
print("")
resumen = df2.groupby('Estado Del Np').agg({'Estado Del Np': 'nunique','Estado Del Np': 'count', 'Valor Total Del NP': 'sum'})
resumen.columns = ['Cantidad', 'Valor Total'] # Renombrar las columnas para que sean claras
resumen = resumen.reset_index() # Resetear el índice para que "ESTADO DEL NP" vuelva a ser una columna

total_general = pd.DataFrame({'Estado Del Np': ['SUMATORIA'],'Cantidad': [resumen['Cantidad'].sum()],'Valor Total': [resumen['Valor Total'].sum()]})

# 2. Concatenar la fila al final del resumen
resumen = pd.concat([resumen, total_general], ignore_index=True)
df2['Estado NP'] = resumen['Estado Del Np']
df2['Cantidad'] = resumen['Cantidad']
df2['Valor Total'] = resumen['Valor Total']


print('********************* FILTRO 2: Profesional frente a estado de NPs ****************')
# 1. Crear la matriz base con totales horizontales
matriz = pd.crosstab(df2['Quien Ingreso Informacion'], df2['Estado Del Np'])
matriz['Nps por profesional'] = matriz.sum(axis=1)
matriz_reset = matriz.reset_index()

# ---- SOLUCIÓN: SUMATORIA VERTICAL INMEDIATA ----

# Creamos la fila de totales calculando la suma vertical de la matriz
fila_totales = matriz_reset.sum(numeric_only=True).to_frame().T

# Asignamos la palabra "SUMATORIA" en la primera columna del índice de profesionales
fila_totales['Quien Ingreso Informacion'] = 'SUMATORIA'

# Agregamos la fila de totales directamente debajo de la matriz (sin dejar filas vacías)
matriz_final = pd.concat([matriz_reset, fila_totales], ignore_index=True)

# 2. Concatenar horizontalmente con tu df2 original
df2 = pd.concat([df2, matriz_final], axis=1)

# 3. Renombrar la columna del índice 34 para evitar nombres duplicados
columnas = list(df2.columns)
columnas[34] = 'Profesional Nps'
df2.columns = columnas


print('********************* FILTRO 3: Contratos frente a Estado de NPs ****************')
matriz = pd.crosstab(df2['Contrato Obra'], df2['Estado Del Np'])
matriz['Nps por contrato'] = matriz.sum(axis=1)
matriz_reset = matriz.reset_index()
indice_nueva_columna = len(df2.columns) # Guardamos cuántas columnas tenía df2 antes de la unión
df2 = pd.concat([df2, matriz_reset], axis=1)
columnas = list(df2.columns) # Usamos el índice que calculamos para renombrar la columna 'Contrato Obra' recién agregada
columnas[indice_nueva_columna] = 'Contrato de Obra vs Estado del NP'
df2.columns = columnas

#df2.to_excel('bloque verde3.xlsx', index=False)

print('********************* FILTRO 4: Nps en revision ****************')

# 1. Agregamos la columna 'Quien Ingreso Informacion' a la extracción y ordenamos
datos_filtrados = df2.loc[df2['Estado Del Np'] == 'EN REVISION',
                         ['Codigo Np', 'Fecha Ingreso C', 'Dias desde el ingreso del NP al IDU', 'Quien Ingreso Informacion', 'Dias de ingreso al grupo np'
                         , 'Dias desde envio correo', 'Contrato Obra', 'Valor Total Del NP', 'Descripcion', 'Objeto', 'Area', 'Mes']
                        ].sort_values(by='Dias desde el ingreso del NP al IDU', ascending=False)

# 2. Creamos las nuevas columnas vacías en df2
df2['Np en Revision'] = None
df2['Fecha de ingreso'] = None
df2['Dias desde el ingreso al IDU'] = None
df2['Profesional NP'] = None
df2['dias de ingreso a grupo NP'] = None
df2['dias de envío correo'] = None
df2['Cto Obra'] = None
df2['Valor NP'] = None
df2['Descripcion np'] = None
df2['Objeto Cto']= None
df2['Subdireccción']= None
df2['Mes del ingreso']= None


# 3. Asignamos los valores filtrados (con .values para que sean consecutivos)
df2.iloc[0:len(datos_filtrados), df2.columns.get_loc('Np en Revision')] = datos_filtrados['Codigo Np'].values
df2.iloc[0:len(datos_filtrados), df2.columns.get_loc('Fecha de ingreso')] = datos_filtrados['Fecha Ingreso C'].values
df2.iloc[0:len(datos_filtrados), df2.columns.get_loc('Dias desde el ingreso al IDU')] = datos_filtrados['Dias desde el ingreso del NP al IDU'].values
df2.iloc[0:len(datos_filtrados), df2.columns.get_loc('Profesional NP')] = datos_filtrados['Quien Ingreso Informacion'].values
df2.iloc[0:len(datos_filtrados), df2.columns.get_loc('dias de ingreso a grupo NP')] = datos_filtrados['Dias de ingreso al grupo np'].values
df2.iloc[0:len(datos_filtrados), df2.columns.get_loc('dias de envío correo')] = datos_filtrados['Dias desde envio correo'].values
df2.iloc[0:len(datos_filtrados), df2.columns.get_loc('Cto Obra')] = datos_filtrados['Contrato Obra'].values
df2.iloc[0:len(datos_filtrados), df2.columns.get_loc('Valor NP')] = datos_filtrados['Valor Total Del NP'].values
df2.iloc[0:len(datos_filtrados), df2.columns.get_loc('Descripcion np')] = datos_filtrados['Descripcion'].values
df2.iloc[0:len(datos_filtrados), df2.columns.get_loc('Objeto Cto')] = datos_filtrados['Objeto'].values
df2.iloc[0:len(datos_filtrados), df2.columns.get_loc('Subdireccción')] = datos_filtrados['Area'].values
df2.iloc[0:len(datos_filtrados), df2.columns.get_loc('Mes del ingreso')] = datos_filtrados['Mes'].values

df2['Fecha Ingreso C'] = pd.to_datetime(df2['Fecha Ingreso C'], errors='coerce') # 1. Asegurar que sea datetime
df2['Fecha Ingreso C'] = df2['Fecha Ingreso C'].dt.strftime('%d-%m-%Y') # 2. Convertir a TEXTO con el formato exacto (elimina las horas)

df2['Fecha de ingreso'] = pd.to_datetime(df2['Fecha de ingreso'], errors='coerce')
df2['Fecha de ingreso'] = df2['Fecha de ingreso'].dt.strftime('%d-%m-%Y')


print('********************* FILTRO 4A: cto de obra frente Nps en revision ****************')
resumen = df2.groupby('Cto Obra').agg({'Cto Obra': 'nunique','Cto Obra': 'count', 'Valor NP': 'sum'})
resumen.columns = ['Np revision', 'Valor Total NP'] # Renombrar las columnas para que sean claras
resumen = resumen.reset_index() # Resetear el índice para que cto obra vuelva a ser una columna

total_general = pd.DataFrame({'Cto Obra': ['SUMATORIA'],'Np revision': [resumen['Np revision'].sum()],'Valor Total NP': [resumen['Valor Total NP'].sum()]})

# 2. Concatenar la fila al final del resumen
resumen = pd.concat([resumen, total_general], ignore_index=True)
df2['Cto de Obra'] = resumen['Cto Obra']
df2['Np revision'] = resumen['Np revision']
df2['Valor Total NP'] = resumen['Valor Total NP']


print('********************* FILTRO 4B: conteo de los dias de ingreso a grupo NP ****************')

# 1. Crear el resumen, resetear índice y ordenar de mayor a menor
resumen_df = df2['Dias desde el ingreso al IDU'].value_counts().reset_index()
resumen_df.columns = ['Dias desde el ingreso', 'Conteo de Nps ingresados']

# 2. Ordenar descendentemente por la columna de individuos
resumen_df = resumen_df.sort_values(by='Dias desde el ingreso', ascending=False)

# 3. Si vas a usar concat con axis=1, recuerda resetear el índice para que empiecen desde 0
resumen_df = resumen_df.reset_index(drop=True)
df2 = pd.concat([df2, resumen_df], axis=1)


print('********************* FILTRO 4C: nps en revision por profesional y valor monetario ****************')

resumen = df2.groupby('Profesional NP').agg({'Profesional NP': 'nunique','Profesional NP': 'count', 'Valor NP': 'sum'})
resumen.columns = ['Nps en revision', 'Valor Total NPs'] # Renombrar las columnas para que sean claras
resumen = resumen.reset_index() # Resetear el índice para que Profesional NP vuelva a ser una columna

total_general = pd.DataFrame({'Profesional NP': ['SUMATORIA'],'Nps en revision': [resumen['Nps en revision'].sum()],'Valor Total NPs': [resumen['Valor Total NPs'].sum()]})

# 2. Concatenar la fila al final del resumen
resumen = pd.concat([resumen, total_general], ignore_index=True)
df2['Profesional precios'] = resumen['Profesional NP']
df2['Nps en revision'] = resumen['Nps en revision']
df2['Valor Total NPs'] = resumen['Valor Total NPs']



print('********************* FILTRO 5: mes de ingreso frente a estado de NP ****************')
print("")

orden_meses = ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio','Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre']
df2['Mes'] = pd.Categorical(df2['Mes'], categories=orden_meses, ordered=True)

# 3. Crear la matriz resumen
matriz = pd.crosstab(df2['Mes'], df2['Estado Del Np'], rownames=['Mes / Estado'])
matriz['Total Nps por mes'] = matriz.sum(axis=1)

# 4. Resetear índice para tener 'Mes / Estado' como columna
matriz_reset = matriz.reset_index()

matriz_reset['Mes / Estado'] = matriz_reset['Mes / Estado'].astype(str)
total_valor = matriz_reset['Total Nps por mes'].sum()

# 6. Crear la fila de sumatoria correctamente en matriz_reset
indice_final = len(matriz_reset)
matriz_reset.loc[indice_final, 'Total Nps por mes'] = total_valor
matriz_reset.loc[indice_final, 'Mes / Estado'] = 'SUMATORIA'

# 5. Concatenar al final
df2 = pd.concat([df2, matriz_reset], axis=1)








print('********************* FILTRO 6: Mes de ingreso del NP frente al profesional  ****************')

orden_meses = ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio','Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre']
# 2. Convertir la columna 'Mes' a categoría ANTES del crosstab
df2['Mes'] = pd.Categorical(df2['Mes'], categories=orden_meses, ordered=True)

# 3. Crear la matriz (ahora los meses saldrán en orden: Enero, Febrero...)
matriz = pd.crosstab(df2['Mes'], df2['Quien Ingreso Informacion'], rownames=['Mes / Profesional'])
matriz['Np prof'] = matriz.sum(axis=1)

# 4. Resetear índice y renombrar
matriz_reset = matriz.reset_index().rename(columns={'Np prof': 'Total Nps / profesional'})

# 5. Concatenar al final
df2 = pd.concat([df2, matriz_reset], axis=1)


print('********************* FILTRO 7: Mes de ingreso del NP frente a Nps contractuales  ****************')
# 1. Extraemos el número y filtramos solo las filas que contienen "CONTRACTUALES"
# 'na=False' evita errores si hay celdas vacías
df_contractuales = df2[df2['Codigo Np'].str.contains("CONTRACTUALES", na=False)].copy()

# 2. Extraer el número del paréntesis y convertirlo a entero
df_contractuales['Cantidad'] = df_contractuales['Codigo Np'].str.extract(r'\((\d+)\)').astype(int)

# 3. Quitar el índice original para que las filas sean consecutivas (0, 1, 2...)
df_contractuales = df_contractuales.reset_index(drop=True)

# 4. Seleccionar solo las columnas que quieres ver (ejemplo: Mes y Cantidad)
resultado_listado = df_contractuales[['Mes', 'Codigo Np', 'Cantidad', 'Quien Ingreso Informacion','Contrato Obra', 'Estado Del Np', 'Dias desde el ingreso del NP al IDU'
, 'Area', 'Consecutivo']]

# 1. Ordenar por la columna 'Consecutivo' (de menor a mayor)
resultado_listado = resultado_listado.sort_values(by='Consecutivo', ascending=True)

# 2. Opcional: Resetear el índice para que las filas vuelvan a ser 0, 1, 2...
resultado_listado = resultado_listado.reset_index(drop=True)

df2 = pd.concat([df2, resultado_listado.add_prefix('Lista_')], axis=1)

#df2.to_excel('bloque verde2.xlsx', index=False)
print('********************* FILTRO 8: Mes de ingreso del NP frente a total NPS contractuales   ****************')
#resumen_por_mes = df2.groupby('Lista_Mes')['Lista_Cantidad'].sum().reset_index() # Crear el resumen de conteo por mes
resumen_por_mes = df2.groupby('Lista_Mes', observed=True)['Lista_Cantidad'].sum().reset_index()
resumen_por_mes.columns = ['Listado Mes', 'NPs Contractuales por Mes'] # 2. Renombrar las columnas para que sean claras

total_row = pd.DataFrame({'Listado Mes': ['SUMATORIA'],'NPs Contractuales por Mes':[resumen_por_mes['NPs Contractuales por Mes'].sum()]})

resumen_por_mes = pd.concat([resumen_por_mes, total_row], ignore_index=True) # Unir la sumatoria al resumen
df2 = pd.concat([df2, resumen_por_mes], axis=1) # Concatenar este resumen a la tu tabla






print('********************* FILTRO 9: profesional frente a NPS contractuales  ****************')
resumen_por_mes = df2.groupby('Lista_Quien Ingreso Informacion')['Lista_Cantidad'].sum().reset_index() # 1. Crear el resumen de conteo por profesional
resumen_por_mes.columns = ['Listado Profesional', 'NPs Contractuales por profesional'] # 2. Renombrar las columnas para que sean claras

# Crear la fila de sumatoria
total_row = pd.DataFrame({'Listado Profesional': ['SUMATORIA'],'NPs Contractuales por profesional': [resumen_por_mes['NPs Contractuales por profesional'].sum()]})

resumen_por_mes = pd.concat([resumen_por_mes, total_row], ignore_index=True) # Unir la sumatoria al resumen
df2 = pd.concat([df2, resumen_por_mes], axis=1)


print('********************* FILTRO 10: Estado del np a NPS contractuales  ****************')
resumen_por_mes = df2.groupby('Lista_Estado Del Np')['Lista_Cantidad'].sum().reset_index() # Crear el resumen de conteo por mes
resumen_por_mes.columns = ['Estado np contractual', 'NPs Contractuales por Estado'] # 2. Renombrar las columnas para que sean claras

# Crear la fila de sumatoria
total_row = pd.DataFrame({'Estado np contractual': ['SUMATORIA'],'NPs Contractuales por Estado': [resumen_por_mes['NPs Contractuales por Estado'].sum()]})

resumen_por_mes = pd.concat([resumen_por_mes, total_row], ignore_index=True) # Unir la sumatoria al resumen
df2 = pd.concat([df2, resumen_por_mes], axis=1) # Concatenar este resumen al lado de tu tabla


print('********************* FILTRO 11: profesional vs dias promedio de ingreso al IDU  ****************')
ingresoIDU = (df2.groupby("Quien Ingreso Informacion")[
        ["Dias desde el ingreso del NP al IDU","Dias de ingreso al grupo np","Dias desde envio correo",]].mean().round(2).reset_index())

ingresoIDU["Dias desde envio correo"] = ingresoIDU["Dias desde envio correo"].round(2)

ingresoIDU = ingresoIDU.rename(columns={"Quien Ingreso Informacion": "Profesional de precios","Dias desde el ingreso del NP al IDU": "Promedio Dias ingreso al IDU",
        "Dias de ingreso al grupo np": "Promedio Dias ingreso al grupo np","Dias desde envio correo": "Promedio Dias de envio correo",})

df2 = pd.concat([df2, ingresoIDU], axis=1)


print('********************* OPERACION 12:  Dias de ingreso al grupo np - Dias desde envio correo ****************')
df2["Dif ingreso-envio correo"] = (df2["Promedio Dias ingreso al grupo np"] - df2["Promedio Dias de envio correo"])



print('********************* 11: graficas varias  ****************')
print("")

# grafica 1
resumen_estado = df2.groupby('Estado NP', observed=False)['Cantidad'].sum().reset_index()
resumen_estado = resumen_estado.sort_values(by='Cantidad', ascending=True) # ordenar ascendentemente

# Crear el gráfico de barras horizontales
ax=resumen_estado.plot(
    kind='barh',
    x='Estado NP',
    y='Cantidad',
    color='skyblue',
    legend=False,
    figsize=(7, 4)) # Ajusta el tamaño para que se lean bien los estados
ax.bar_label(ax.containers[0], padding=3) # 'padding=3' separa un poco el número de la barra

# Darle un poco más de espacio al eje X para que el número no se corte
plt.xlim(0, resumen_estado['Cantidad'].max() * 1.15)

# Detalles estéticos
plt.title('Cantidad NPs por Estado')
plt.xlabel('Cantidad')
plt.ylabel('Estado NP')
plt.grid(axis='x', linestyle='--', alpha=0.7) # Rejilla vertical para ayudar a la lectura
plt.tight_layout() # Ajusta el margen para que no se corten los nombres de los estados
ax.tick_params(axis='y', labelsize=8)
#plt.show()
st.pyplot(fig)


# grafica 2
resumen_estado = df2.groupby('Estado NP', observed=False)['Valor Total'].sum().reset_index()
resumen_estado = resumen_estado.sort_values(by='Valor Total', ascending=True) # ordenar ascendentemente

# Crear el gráfico de barras horizontales
ax=resumen_estado.plot(
    kind='barh',
    x='Estado NP',
    y='Valor Total',
    color='lightcoral',
    legend=False,
    figsize=(9, 5)) # Ajusta el tamaño para que se lean bien los estados

# Creamos una lista de etiquetas con formato: $ 1,234,567
labels = [f'${x:,.0f}' for x in resumen_estado['Valor Total']]
ax.bar_label(ax.containers[0], labels=labels, padding=3)

plt.xlim(0, resumen_estado['Valor Total'].max() * 1.15) # Darle un poco más de espacio al eje X para que el número no se corte

# Detalles estéticos
plt.title(' total valor monetario por Estado NP')
plt.xlabel('Valor Total')
plt.ylabel('Estado NP')
plt.grid(axis='x', linestyle='--', alpha=0.7) # Rejilla vertical para ayudar a la lectura
plt.tight_layout() # Ajusta el margen para que no se corten los nombres de los estados
ax.tick_params(axis='y', labelsize=8)
#plt.show()
st.pyplot(fig)



# grafica 3
resumen_estado = df2.groupby('Listado Mes', observed=False)['NPs Contractuales por Mes'].sum().reset_index()
resumen_estado = resumen_estado.sort_values(by='NPs Contractuales por Mes', ascending=True) # ordenar ascendentemente

# Crear el gráfico de barras horizontales
ax=resumen_estado.plot(kind='barh',x='Listado Mes',y='NPs Contractuales por Mes',color='orchid',legend=False,figsize=(7, 5))
ax.bar_label(ax.containers[0], padding=3) # 'padding=3' separa un poco el número de la barra

# Darle un poco más de espacio al eje X para que el número no se corte
plt.xlim(0, resumen_estado['NPs Contractuales por Mes'].max() * 1.15)

# Detalles estéticos
plt.title(' NPs contractuales por mes')
plt.xlabel('NPs Contractuales por Mes')
plt.ylabel('Listado Mes')
plt.grid(axis='x', linestyle='--', alpha=0.7) # Rejilla vertical para ayudar a la lectura
plt.tight_layout() # Ajusta el margen para que no se corten los nombres de los estados
ax.tick_params(axis='y', labelsize=9)
#plt.show()
st.pyplot(fig)




# grafica 4
resumen_estado = df2.groupby('Profesional Nps', observed=False)['Nps por profesional'].sum().reset_index()
resumen_estado = resumen_estado.sort_values(by='Nps por profesional', ascending=True) # ordenar ascendentemente

# Crear el gráfico de barras horizontales
ax=resumen_estado.plot(
    kind='barh',
    x='Profesional Nps',
    y='Nps por profesional',
    color='lightgreen',
    legend=False,
    figsize=(8, 4)) # Ajusta el tamaño para que se lean bien los estados

ax.bar_label(ax.containers[0], padding=3)

# Darle un poco más de espacio al eje X para que el número no se corte
plt.xlim(0, resumen_estado['Nps por profesional'].max() * 1.15)

# Detalles estéticos
plt.title(' Cantidad de NPs por Profesional')
plt.xlabel('Nps por profesional')
plt.ylabel('Profesional Nps')
plt.grid(axis='x', linestyle='--', alpha=0.7) # Rejilla vertical para ayudar a la lectura
plt.tight_layout() # Ajusta el margen para que no se corten los nombres de los estados
ax.tick_params(axis='y', labelsize=7)
#plt.show()
st.pyplot(fig)



# grafica 5
resumen_estado = df2.groupby('Cto de Obra', observed=False)['Np revision'].sum().reset_index()
resumen_estado = resumen_estado.sort_values(by='Np revision', ascending=True) # ordenar ascendentemente

# Crear el gráfico de barras horizontales
ax=resumen_estado.plot(
    kind='barh',
    x='Cto de Obra',
    y='Np revision',
    color='thistle',
    legend=False,
    figsize=(7, 5)) # Ajusta el tamaño para que se lean bien los estados

ax.bar_label(ax.containers[0], padding=3)

# Darle un poco más de espacio al eje X para que el número no se corte
plt.xlim(0, resumen_estado['Np revision'].max() * 1.15)

# Detalles estéticos
plt.title(' NPs en revisión por contrato')
plt.xlabel('Np revision')
plt.ylabel('Cto de Obra')
plt.grid(axis='x', linestyle='--', alpha=0.7) # Rejilla vertical para ayudar a la lectura
plt.tight_layout() # Ajusta el margen para que no se corten los nombres de los estados
ax.tick_params(axis='y', labelsize=8)
#plt.show()
st.pyplot(fig)



# grafica 6
resumen_estado = df2.groupby('Cto de Obra', observed=False)['Valor Total NP'].sum().reset_index()
resumen_estado = resumen_estado.sort_values(by='Valor Total NP', ascending=True) # ordenar ascendentemente
# Crear el gráfico de barras horizontales
ax=resumen_estado.plot(kind='barh',x='Cto de Obra',y='Valor Total NP',color='royalblue',legend=False,figsize=(7, 5))

# Creamos una lista de etiquetas con formato: $ 1,234,567
labels = [f'${x:,.0f}' for x in resumen_estado['Valor Total NP']]
ax.bar_label(ax.containers[0], labels=labels, padding=3)

# Darle un poco más de espacio al eje X para que el número no se corte
plt.xlim(0, resumen_estado['Valor Total NP'].max() * 1.15)

# Detalles estéticos
plt.title(' Valor monetario por contrato')
plt.xlabel('Valor Total NP')
plt.ylabel('Cto de Obra')
plt.grid(axis='x', linestyle='--', alpha=0.7) # Rejilla vertical para ayudar a la lectura
plt.tight_layout() # Ajusta el margen para que no se corten los nombres de los estados
ax.tick_params(axis='y', labelsize=8)
#plt.show()
st.pyplot(fig)



# grafica 7
resumen_estado = df2.groupby('Mes / Estado', observed=False)['Total Nps por mes'].sum().reset_index()
resumen_estado = resumen_estado.sort_values(by='Total Nps por mes', ascending=True) # ordenar ascendentemente
ax=resumen_estado.plot(kind='barh',x='Mes / Estado',y='Total Nps por mes',color='coral',legend=False,figsize=(7, 4)) # Ajusta el tamaño
ax.bar_label(ax.containers[0], padding=3)

# Darle un poco más de espacio al eje X para que el número no se corte
plt.xlim(0, resumen_estado['Total Nps por mes'].max() * 1.15)

# Detalles estéticos
plt.title(' Ingreso de NPs por mes')
plt.xlabel('Total Nps por mes')
plt.ylabel('Mes / Estado')
plt.grid(axis='x', linestyle='--', alpha=0.7) # Rejilla vertical para ayudar a la lectura
plt.tight_layout() # Ajusta el margen para que no se corten los nombres de los estados
ax.tick_params(axis='y', labelsize=8)
#plt.show()
st.pyplot(fig)




# PASO FINAL: Guardar el archivo organizado y actualizado.
df2.to_excel('bloque verde.xlsx', index=False)





# grafica 8: Gráfico de Sankey o de categorias paralelas PROFESIONAL FRENTE A NPS CONTRACTUALES Y NPS-----------------------------------------
df_sankey = df2.groupby(['NPs Contractuales por profesional', 'Profesional Nps', 'Nps por profesional'])['NPs Contractuales por profesional'].sum().reset_index(name='Frec')
fig = px.parallel_categories(df_sankey,
                             dimensions=['NPs Contractuales por profesional', 'Profesional Nps', 'Nps por profesional'],
                             labels={'NPs Contractuales por profesional':'NPs Contractuales asignados', 'Profesional Nps':'Profesional', 'Nps por profesional':'NPS asignados'},
                             color='Frec', color_continuous_scale=px.colors.sequential.RdPu, width=750, height=380)
fig.update_layout(coloraxis_showscale=False) # linea para ocultar la escala de la grafica
fig.update_traces(labelfont=dict(family='Arial, Gadget, sans-serif',size=13,color='black'))
#fig.show()
st.plotly_chart(fig)



# grafica 9: Gráfico de Sankey o de categorias paralelas MES FRENTE A NPS CONTRACTUALES Y NPS-----------------------------------------
df_sankey = df2.groupby(['Total Nps por mes', 'Mes / Estado', 'NPs Contractuales por Mes'])['Total Nps por mes'].sum().reset_index(name='Frec')
fig = px.parallel_categories(df_sankey,
                             dimensions=['Total Nps por mes', 'Mes / Estado', 'NPs Contractuales por Mes'],
                             labels={'Total Nps por mes':'NPS por mes', 'Mes / Estado':'Nombre Mes', 'NPs Contractuales por Mes':'# de nps contractuales por mes'},
                             color='Frec', color_continuous_scale=px.colors.sequential.GnBu, width=600, height=380)
fig.update_layout(coloraxis_showscale=False)
fig.update_traces(labelfont=dict(family='Arial, Gadget, sans-serif',size=13,color='black'))
#fig.show()
st.plotly_chart(fig)




# grafica 10: Gráfico de Sankey o de categorias paralelas CONTRATO FRENTE A NP REVISION Y SU VALOR MONETARIO   col BS, BT, BU-----------------------------------------
df_sankey = df2.groupby(['Np revision', 'Cto de Obra', 'Valor Total NP'])['Np revision'].sum().reset_index(name='Frec')
df_sankey['Valor Total NP'] = df_sankey['Valor Total NP'].map('${:,.0f}'.format)

fig = px.parallel_categories(df_sankey,
                             dimensions=['Np revision', 'Cto de Obra', 'Valor Total NP'],
                             labels={'Np revision':'NP en revision', 'Cto de Obra':'Contrato de obra',  'Valor Total NP':'Valor NPS en revision'},
                             color='Frec', color_continuous_scale=px.colors.sequential.YlGnBu, width=600, height=650)
fig.update_layout(coloraxis_showscale=False)
fig.update_traces(labelfont=dict(family='Arial, Gadget, sans-serif',size=13,color='black'))
#fig.show()
st.plotly_chart(fig)




# grafica 11: Gráfico de Sankey o de categorias paralelas PROFESIONAL PRECIOS FRENTE NPS EN REVISION Y SUS VALORES MONETARIOS -----------------------------------------
df_sankey = df2.groupby(['Nps en revision', 'Profesional precios', 'Valor Total NPs'])['Nps en revision'].sum().reset_index(name='Frec')
df_sankey['Valor Total NPs'] = df_sankey['Valor Total NPs'].map('${:,.0f}'.format)

fig = px.parallel_categories(df_sankey,
                             dimensions=['Nps en revision', 'Profesional precios', 'Valor Total NPs'],
                             labels={'Nps en revision':'NP en revision', 'Profesional precios':'Profesional de precios',  'Valor Total NPs':'Valor NPS en revision'},
                             color='Frec', color_continuous_scale=px.colors.sequential.PuBu, width=750, height=380)
fig.update_layout(coloraxis_showscale=False)
fig.update_traces(labelfont=dict(family='Arial, Gadget, sans-serif',size=13,color='black'))
#fig.show()
st.plotly_chart(fig)



# grafica 12: Gráfico de Sankey o de categorias paralelas Estado NP cantidad y valor monetario-----------------------------------------
df_sankey = df2.groupby(['Cantidad', 'Estado NP', 'Valor Total'])['Cantidad'].sum().reset_index(name='Frec')
df_sankey['Valor Total'] = df_sankey['Valor Total'].map('${:,.0f}'.format)

fig = px.parallel_categories(df_sankey,
                             dimensions=['Cantidad', 'Estado NP', 'Valor Total'],
                             labels={'Cantidad':'NP ingresados al IDU','Estado NP':'Estado actual NPS ingresados','Valor Total':'Valor monetario NPS ingresados'},
                             color='Frec', color_continuous_scale=px.colors.sequential.Peach, width=750, height=420)
fig.update_layout(coloraxis_showscale=False)
fig.update_traces(labelfont=dict(family='Arial, Gadget, sans-serif',size=13,color='black'))
#fig.show()
st.plotly_chart(fig)





# grafica 12: Gráfico de burbujas (Bubble Chart 1D)
# sequential.Blues, sequential.PuBu, sequential.RdPu, px.colors.sequential.Mint, px.colors.sequential.Teal, px.colors.sequential.GnBu
#sequential.YlOrRd, sequential.YlOrBr, sequential.Solar, sequential.YlGn, sequential.YlGnBu, sequential.Oranges, sequential.Peach, sequential.OrRd

df2['NPs Contractuales por Mes'] = df2['NPs Contractuales por Mes'].fillna(0)
df2['Listado Mes'] = df2['Listado Mes'].astype(str)

fig = px.scatter(df2, x="Listado Mes", y=[0] * len(df2), size="NPs Contractuales por Mes", color="NPs Contractuales por Mes",
                 text="NPs Contractuales por Mes", hover_name="Listado Mes", size_max=60, width=1250, height=350,
                 color_continuous_scale=px.colors.sequential.RdPu, labels={'NPs Contractuales por Mes': 'Total NPs', 'x': 'Mes'})

fig.update_layout(height=250, yaxis={'visible': False, 'showgrid': True, 'zeroline': True}, xaxis={'showgrid': True}, plot_bgcolor='white',
                  title="Ingreso Mensual de NPs Contractuales 2026")

fig.update_xaxes(showline=True, linewidth=1, linecolor='black', mirror=True)
fig.update_yaxes(showline=True, linewidth=1, linecolor='black', mirror=True)
#fig.show()
st.plotly_chart(fig)



# grafica 13: Gráfico de burbujas (Bubble Chart 1D)
df2['Total Nps por mes'] = df2['Total Nps por mes'].fillna(0)
df2['Mes / Estado'] = df2['Mes / Estado'].astype(str)

fig = px.scatter(df2, x="Mes / Estado", y=[0] * len(df2), size="Total Nps por mes", color="Total Nps por mes",
                 text="Total Nps por mes", hover_name="Mes / Estado", size_max=60, width=800, height=350,
                 color_continuous_scale=px.colors.sequential.YlOrBr, labels={'Total Nps por mes': 'Total NPs', 'x': 'Mes'})

fig.update_layout(height=250, yaxis={'visible': False, 'showgrid': True, 'zeroline': True}, xaxis={'showgrid': False}, plot_bgcolor='white',
                  title="Ingreso Mensual de NPs")

fig.update_xaxes(showline=True, linewidth=1, linecolor='black', mirror=True)
fig.update_yaxes(showline=True, linewidth=1, linecolor='black', mirror=True)
#fig.show()
st.plotly_chart(fig)








print("*******************  INFORMACION GENERAL DEL BLOQUE VERDE DE LOS NPS:  *********************")
print("")
print(df2.info())
print("")
print("fin del programa")

